config/routes.rb
Rails.application.routes.draw do
  resources :postings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'postings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/posting.rb
class Posting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  before_action :set_posting, only: [:show, :edit, :update, :destroy]

  # GET /postings
  # GET /postings.json
  def index
    @postings = Posting.all.order(created_at: :desc)
  end

  # GET /postings/1
  # GET /postings/1.json
  def show
    heading = "<h3>#{@posting.company_name} is hiring #{@posting.position_name}.</h3>"
    apply_button = "<a href=\"#{@posting.link}\" rel=\"nofollow\"><img src='https://i.imgur.com/eNHwjtX.png'/></a><br><br>"
    # job summary
    job_summary = "<h3>#{@posting.summary_name}</h3><p>#{@posting.summary}</p>"

    job_duties = generate_html(@posting.radio_duties, @posting.duties, @posting.duties_name)
    qualifications = generate_html(@posting.radio_qualifications, @posting.qualifications, @posting.qualifications_name)
    additional_comments = generate_html(@posting.radio_additional_comments, @posting.additional_comments, @posting.additional_comments_name)
    last_section = generate_html(@posting.radio_last_section, @posting.last_section, @posting.last_section_name)

    @html = heading
    @html += job_summary
    @html += job_duties
    @html += qualifications
    @html += additional_comments
    @html += last_section
    @html += "<p>Please apply with your resume and profile via #{@posting.company_name}'s <b><i>"
    @html += "one minute application</i></b> today:</p>"
    @html += apply_button
    @html += "<p>Take control of your hospitality career with your professional EightSix Profile: stand out from the competition, track your profile views, and get alerted to opportunities by #{@posting.company_name} and many other great employers as they become available. EightSix empowers you to showcase your talents and get hired for what you bring to the table.</p>"
    @html += "<p>The best employers meet their top candidates on <b>EightSix Network - The Industry's professional employment network.</i> Join today.</p>"
    @html_render = @html.html_safe
  end #end show

  # GET /postings/new
  def new
    @posting = Posting.new
  end

  # GET /postings/1/edit
  def edit
  end

  # POST /postings
  # POST /postings.json
  def create
    @posting = Posting.new(posting_params)

    respond_to do |format|
      if @posting.save
        format.html { redirect_to @posting, notice: 'Posting was successfully created.' }
        format.json { render :show, status: :created, location: @posting }
      else
        format.html { render :new }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postings/1
  # PATCH/PUT /postings/1.json
  def update
    respond_to do |format|
      if @posting.update(posting_params)
        format.html { redirect_to @posting, notice: 'Posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @posting }
      else
        format.html { render :edit }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postings/1
  # DELETE /postings/1.json
  def destroy
    @posting.destroy
    respond_to do |format|
      format.html { redirect_to postings_url, notice: 'Posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posting
      @posting = Posting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def posting_params
      params.require(:posting).permit(:company_name, :position_name, :link, :summary, :summary_name, :qualifications, :qualifications_name, :duties, :last_section, :duties_name, :additional_comments, :additional_comments_name, :last_section_name, :radio_duties, :radio_summary, :radio_qualifications, :radio_additional_comments, :radio_last_section)
    end

    # generates html markup for text section from input data
    def generate_html(type, text, title)
      markup = ""
      if text.length > 0
        # title
        markup += "<h3>#{title}</h3>"

        if type == 'point-form'
          # if point form was selected
          markup += "<ul>"
          # split strings
          point_form_array = text.split(/^•|^-|^/)
          point_form_array.reject!{ |item| item.nil? || item == '' }

          point_form_array.each do |point_form|
            markup += "<li>#{point_form}</li>"
          end

          markup += "</ul>"
        elsif type == 'paragraphs'
          # if paragraphs were selected
          markup += "<p>#{text}</p>"
        end
      end
      # return html markup
      markup
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobPostingGenerator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/postings/_form.html.erb
<%= form_with(model: posting, local: true, class: 'form-group') do |form| %>
  <div class="col-sm-12 col-md-10 col-lg-8 offset-lg-2 offset-md-1">
    <% if posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(posting.errors.count, "error") %> prohibited this posting from being saved:</h2>

      <ul>
        <% posting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <h2>Primary Information</h2>
    <div class="field">
      <%= form.label :company_name %>
      <%= form.text_field :company_name, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :position_name %>
      <%= form.text_field :position_name, class: 'form-control', placeholder: "Please prefix 'a/an' as necessary to the position name" %>
    </div>

    <div class="field">
      <%= form.label :link, 'Job Posting Link' %>
      <%= form.text_field :link, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :summary_name, 'Posting Header Paragraph' %>
      <%= form.text_field :summary_name, class: 'form-control', placeholder: 'Optional title' %>
    </div>

    <div class="field">
      <%= form.text_area :summary, class: 'form-control', placeholder: 'Please do not enter point form here' %>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>

    <h2>Optional Information</h2>

    <hr>

    <div class="field">
      <%= form.label :duties_name, 'Additional Section 1' %>
      <%= form.text_field :duties_name, class: 'form-control', placeholder: 'Optional title' %>
    </div>

    <div class="field">
      <div class="row">
        <div class="col-3">
          <%= form.label :radio_duties, 'Paragraphs' %>
          <%= form.radio_button :radio_duties, 'paragraphs' %>
        </div>

        <div class="col-3">
          <%= form.label :radio_duties, 'Point-form' %>
          <%= form.radio_button :radio_duties, 'point-form', :checked => 'checked' %>
        </div>
      </div>
    </div>

    <div class="field">
      <%= form.text_area :duties, class: 'form-control' %>
    </div>

    <hr>

    <div class="field">
      <%= form.label :qualifications_name, 'Additional Section 2' %>
      <%= form.text_field :qualifications_name, class: 'form-control', placeholder: 'Optional title' %>
    </div>

    <div class="field">
      <div class="row">
        <div class="col-3">
          <%= form.label :radio_qualifications, 'Paragraphs' %>
          <%= form.radio_button :radio_qualifications, 'paragraphs' %>
        </div>

        <div class="col-3">
          <%= form.label :radio_qualifications, 'Point-form' %>
          <%= form.radio_button :radio_qualifications, 'point-form', :checked => 'checked' %>
        </div>
      </div>
    </div>

    <div class="field">
      <%= form.text_area :qualifications, class: 'form-control' %>
    </div>

    <hr>

    <div class="field">
      <%= form.label :additional_comments_name, 'Additional Section 3' %>
      <%= form.text_field :additional_comments_name, class: 'form-control', placeholder: 'Optional title' %>
    </div>

    <div class="field">
      <div class="row">
        <div class="col-3">
          <%= form.label :radio_additional_comments, 'Paragraphs' %>
          <%= form.radio_button :radio_additional_comments, 'paragraphs' %>
        </div>

        <div class="col-3">
          <%= form.label :radio_additional_comments, 'Point-form' %>
          <%= form.radio_button :radio_additional_comments, 'point-form', :checked => 'checked' %>
        </div>
      </div>
    </div>

    <div class="field">
      <%= form.text_area :additional_comments, class: 'form-control', placeholder: 'Please do not enter point form' %>
    </div>

    <hr>
    <div class="field">
      <%= form.label :last_section_name, 'Additional Section 4' %>
      <%= form.text_field :last_section_name, class: 'form-control', placeholder: 'Optional title' %>
    </div>

    <div class="field">
      <div class="row">
        <div class="col-3">
          <%= form.label :radio_last_section, 'Paragraphs' %>
          <%= form.radio_button :radio_last_section, 'paragraphs' %>
        </div>

        <div class="col-3">
          <%= form.label :radio_last_section, 'Point-form' %>
          <%= form.radio_button :radio_last_section, 'point-form', :checked => 'checked' %>
        </div>
      </div>
    </div>

    <div class="field">
      <%= form.text_area :last_section, class: 'form-control', placeholder: 'Please do not enter point form' %>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/postings/edit.html.erb
<h1>Editing Posting</h1>
<div class="btn-group">
  <%= link_to 'Show', @posting, class: 'btn btn-secondary btn-sm' %>
  <%= link_to 'Back', postings_path, class: 'btn btn-secondary btn-sm' %>
</div>

<%= render 'form', posting: @posting %>

app/views/postings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Postings</h1>
<%= link_to 'New Posting', new_posting_path, class: 'btn btn-secondary btn-sm' %>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Position name</th>
      <th>Link</th>
      <th>Summary</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @postings.each do |posting| %>
      <tr>
        <td><%= posting.company_name %></td>
        <td><%= posting.position_name %></td>
        <td><a href="<%= posting.link %>" class="btn btn-secondary btn-sm">Link</a></td>
        <td><%= posting.summary %></td>
        <td>
          <div class="btn-group" role="group">
            <%= link_to 'Show', posting, class: 'btn btn-secondary btn-sm' %>
            <%= link_to 'Edit', edit_posting_path(posting), class: 'btn btn-secondary btn-sm' %>
            <%= link_to 'Delete', posting, method: :delete, class: 'btn btn-secondary btn-sm', data: { confirm: 'Are you sure?' } %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/postings/new.html.erb
<h1 style="text-align:center">New Posting</h1>
<div class="row">
  <div class="col-10 offset-2">
    <%= link_to 'Back', postings_path, class: 'btn btn-secondary' %>
  </div>
</div>
<br>
<%= render 'form', posting: @posting %>

app/views/postings/show.html.erb
<h1>Show Posting</h1>
<div class="row">
  <div class="btn-group">
    <%= link_to 'Edit', edit_posting_path(@posting), class: 'btn btn-secondary btn-sm' %>
    <%= link_to 'Back', postings_path, class: 'btn btn-secondary btn-sm'%>
  </div>
</div>
<div class="row">
  <div class="col-lg-10 offset-lg-1">
    <h3>Preview</h3>
    <div class="craigslist-preview">
      <%= @html_render %>
    </div>

    <h3>Html code:</h3>
    <p>
      <%= @html %>
    </p>

<!--     <button class="btn btn-primary" style="background-color:#3971B4;text-transform:uppercase;font-size:28px;padding:30px;font-weight:normal;border-radius:10px;font-style:sans-serif;font-family:'Roboto', sans-serif;">
      Apply Now
    </button> -->
  </div>
</div>